app:
  es:
    video-index: videos_info
    live-index: lives_info
    goods-index: good
    article-index: article3
    reportlabel-index: reportlabel
  redis:
    expire-days: 15
  kafka:
    topic:
      article-rcmd-request: article-rcmd-request


logging:
  level:
    org:
      springframework: ERROR
    com:
      haozhuo: DEBUG
  file: /data/work/luciuschina/spring-apps/tmp/recommder.log

spring:
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.1.150:26379,192.168.1.152:26379,192.168.1.153:26379
  datasource:
    dataetl:
      url: jdbc:mysql://192.168.1.162:3306/yjk_data_etl
      username: datag
      password: yjkdatag
      maximum-pool-size: 15
  kafka:
    bootstrap-servers: 192.168.1.152:9092,192.168.1.153:9092
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.152:9300,192.168.1.153:9300
      cluster-name: hz-es-cluster1


