app:
  es:
    video-index: video4
    live-index: live4
    goods-index: goods5
    article-index: article4
    reportlabel-index: reportlabel
    goods-search-fields: name,category,goodsTags,searchKeywords,description
  mysql:
    article: article4
    video: video4
    live: live4
    goods: goods5
  redis:
    expire-days: 15
    pushed-key-max-size: 200
  kafka:
    topic:
      news-rcmd-request: news-rcmd-request
      prefs-update: prefs-update
      userBehaviorTopic: dev-syn-table-userBehavior
      userBehaviorTopicTest: test-syn-table-userBehavior1 
  biz:
    send-rcmd-msg: false
    goods-sales-days: 90
    queue-rcmd-num: 5,4,3,3
    article-tags: title,tags,keywords
  rest:
    glu: http://192.168.1.178:10011/getReportContent?healthReportId=%s

logging:
  level:
    org:
      springframework: ERROR
    com:
      haozhuo: DEBUG
  file: tmp/recommder.log

spring:
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.1.150:26379,192.168.1.152:26379
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
  datasource:
    dataetl:
      url: jdbc:mysql://192.168.1.162:3306/yjk_data_etl?characterEncoding=utf-8
      username: datag
      password: yjkdatag
      maximum-pool-size: 15
    bisys:
      url: jdbc:mysql://192.168.1.162:3306/bisys?characterEncoding=utf-8
      username: datag
      password: yjkdatag
      maximum-pool-size: 15
    yjk-mall:
      url: jdbc:mysql://192.168.1.201:3306/yjk_mall_2_0?characterEncoding=utf-8
      username: root
      password: mysql4hz@2015
      maximum-pool-size: 1
    whhaozhuo:
      url: jdbc:mysql://192.168.1.162:3306/whhaozhuo?characterEncoding=utf-8
      username: datag
      password: yjkdatag
      maximum-pool-size: 1
  kafka:
    bootstrap-servers: 192.168.1.153:9092
  data:
    elasticsearch:
      cluster-nodes: es1:9300,es2:9300,es3:9300
      cluster-name: hz-datag-es

hbase:
  zookeeper:
    quorum: 192.168.1.150
    port:  2181
  rpc:
    timeout: 1800000
  client:
    scanner:
      timeout:
        period: 1800000
