app:
  es:
    video-index: video4
    live-index: live4
    goods-index: goods5
    article-index: article5
    reportlabel-index: reportlabel
    goods-search-fields: name,category,goodsTags,searchKeywords,description
  mysql:
    article: article5
    video: video4
    live: live4
    goods: goods5
  redis:
    expire-days: 15
    pushed-key-max-size: 200
  kafka:
    topic:
      news-rcmd-request: news-rcmd-request
      prefs-update: prefs-update
      userBehaviorTopic: dev-syn-table-userBehavior
      userBehaviorTopicTest: test-syn-table-userBehavior1 
      reportTopic: report-sink
  biz:
    send-rcmd-msg: false
    goods-sales-days: 90
    queue-rcmd-num: 5,4,3,3
    article-tags: title,tags,keywords
  rest:
    glu: http://192.168.1.178:10011/getReportContent?healthReportId=%s

logging:
  level:
    org:
      springframework: ERROR
    com:
      haozhuo: DEBUG
  file: tmp/recommder.log

spring:
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.1.150:26379,192.168.1.152:26379
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
  datasource:
    dataetl:
      url: jdbc:mysql://rm-uf64qwlstnkq2n35uzo.mysql.rds.aliyuncs.com:3306/yjk_data_etl?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      username: datag
      password: yjkdatag
      maximum-pool-size: 15
    bisys:
      url: jdbc:mysql://rm-uf64qwlstnkq2n35uzo.mysql.rds.aliyuncs.com/bisys?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      username: datag
      password: yjkdatag
      maximum-pool-size: 15
    yjk-mall:
      url: jdbc:mysql://rm-uf64qwlstnkq2n35uzo.mysql.rds.aliyuncs.com:3306/yjk_mall_2_0?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      username: root
      password: mysql4hz@2015
      maximum-pool-size: 1
    whhaozhuo:
      url: jdbc:mysql://rm-uf64qwlstnkq2n35uzo.mysql.rds.aliyuncs.com:3306/whhaozhuo?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      username: datag
      password: yjkdatag
      maximum-pool-size: 5
    rptstd:
      url: jdbc:mysql://rm-uf64qwlstnkq2n35uzo.mysql.rds.aliyuncs.com:3306/report_content_kafka?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      username: datag
      password: yjkdatag
      maximum-pool-size: 10
    yjkrepot:
      url: jdbc:mysql://192.168.1.170:3306/yjk_big?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      username: yjk_user
      password: user_pa$$w0rd
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: 192.168.1.152:9092
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.152:9300,192.168.1.153:9300
      cluster-name: hz-es-cluster1

hbase:
  zookeeper:
    quorum: 192.168.1.150
    port:  2181
  rpc:
    timeout: 1800000
  client:
    scanner:
      timeout:
        period: 1800000
