app:
  es:
    video-index: video4
    live-index: lives_info
    goods-index: good
    article-index: article4
    reportlabel-index: reportlabel
  mysql:
    article: article4
    video: video4
    live: lives_info
  redis:
    expire-days: 15
  kafka:
    topic:
      article-rcmd-request: article-rcmd-request
  rest:
    glu: http://192.168.1.178:10011/getReportContent?healthReportId=%s


logging:
  level:
    org:
      springframework: ERROR
    com:
      haozhuo: DEBUG
  file: /data/work/luciuschina/spring-apps/tmp/recommder.log

spring:
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.1.150:26379,192.168.1.152:26379,192.168.1.153:26379
    pool:
      max-idle: 8
      max-active: 8
      min-idle: 0
  datasource:
    dataetl:
      url: jdbc:mysql://192.168.1.162:3306/yjk_data_etl?characterEncoding=utf-8
      username: datag
      password: yjkdatag
      maximum-pool-size: 15
    bisys:
      url: jdbc:mysql://192.168.1.162:3306/bisys?characterEncoding=utf-8
      username: datag
      password: yjkdatag
      maximum-pool-size: 2
  kafka:
    bootstrap-servers: 192.168.1.152:9092,192.168.1.153:9092
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.152:9300,192.168.1.153:9300
      cluster-name: hz-es-cluster1


